### ISSUE TITLE
Wrong CLI output

### ISSUE THREAD

**Issue by FabianWilkens** [YunoHost-Apps/ifconfig-io_ynh#9] opened 2022-11-17 18:34 UTC
For example the output of `curl example.tld` should be `1.2.3.4` (IP Address)
This dosn't work anymore because of redirect from http to https.
`curl https://example.tld` is working correctly.

**Comment by FabianWilkens** [comment] 2022-11-17 18:42
@alexAubin 
I belive this problem exists since the implement of the global settings for https redirect Yunohost/yunohost#1304, but haven`t noticed it before.
Do you think it is somehow possible to allow http instead of https for an app or a domain.

**Comment by alexAubin** [comment] 2022-12-08 19:19
Imho this is the expected behavior and not a bug

- Disabling HTTPS redirection worsens the situation - it's almost 2023, people should be using HTTPS by default, period
- Querying website using HTTP is insecure and prone to MITM. So by making `curl example.tld` "work", you're effectively allowing these kinds of attacks
- If you really want to have curl working without `https://`, then use the `-L` option to autofollow redirect
- ... but still, how big of a deal is it that people should type `https://` anyway ... ?
- Alternatively, the curl folks should really consider defaulting to https by default instead of http ... but I guess that would break too many stuff in the wild

**Comment by Typhlos** [comment] 2023-03-19 12:29
I just thought of a solution : ifconfig-io uses the HOSTNAME variable for the CLI output. We could just add https:// in this variable and it would output the correct CLI. I'm waiting to see if #12 will be merged and I'll make a PR for that too

**Closed** 2023-04-16 06:46 UTC
